- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/customers/CustomerDbConnector.groovy
This aim of this PR is to remove the access to the outdated `unknown` member of the `Affiliation Category `enum in `qoffer-2-portlet.`
The missing category was updated to `external academic` in the database. 
Misc:
The Exception case is theoretically not necessary anymore, since the category should be determined before adding an entry to the SQL Database
I kept it since i think it makes sense to provide a concise logging to doublecheck the entries during the transition period from one database to another.
> Remove the unknown setting of an affiliation Category in CustomerDBConnector if no category was set

- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/customers/CustomerDbConnector.groovy
**Purpose of change**
This PR removes the unnecessary `toString` casting of the `customerId` in the statement generation for the `getAffiliationIdsForPerson `method in `CustomerDBConnector`.
> Remove unnecessary toString casting of customerId in CustomerDBConnector

- pom.xml
This PR updates the Groovy version to 3.0.7 which addresses some security vulnerabilities.
> Bump Groovy version 3.0.6 to 3.0.7

- qoffer-infrastructure/src/main/resources/offer-template/offer.html
**Purpose**
This PR makes sure all dynamic fields in the html doc are provided to properly present the offer DTO. This allows to easily load dynamic content into the html template.
**Changes**
The ids are named in a manner to provide consistent naming conventions (separation with a hyphen). Finally, the item table contains now `thead` and `tbody` to allow dynamic adding of table rows for items.
> Add ids for dynamic fields

- qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/Offer.groovy
- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferDbConnector.groovy
**Purpose of change**
The vat, net prices, and overheads should be stored in the database and be fetched when loading an offer from the DB
**Changes**
The corresponding queries are updated to obtain the values and write them to the database accordingly
> add vat, net and overheads to db queries

- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferToPDFConverter.groovy
- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/CustomerSelectionView.groovy
This PR replaces the internal `AcademicTitle `of `None`with an empty String for a Customer in the `CustomerSelectionView` and the Customer and ProjectManager in the finalized Offer Document. 
Note that there is currently in issue in terms of the shown `AcademicTitle` in the` CustomerSelectionView`, See #209
> Replace "None" Title with an empty String in final Offer document and CustomerSelectionView

- qoffer-domain/src/main/groovy/life/qbic/portal/portlet/products/ListProducts.groovy
- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/DependencyManager.groovy
**Purpose**
Fix #212 
**Changes**
The `ListProductController` is associated with the `CreateOffer` use case. Therefore, duplicating the use case itself is not sufficient. I updated the `ListProductController` in such a way that it can serve multiple `CreateOffer` use cases
**Additional Information**
It should be considered to use the Publish-Subscribe pattern also for listing the products. Furthermore, we should think about having an `UpdateOffer` use case to be more specific in our code and separate functionality.
> Show product items when updating offer

- qoffer-infrastructure/src/main/resources/offer-template/offer.html
- qoffer-infrastructure/src/main/resources/offer-template/stylesheet.css
This PR enables proper font family usage when rendering an offer to PDF.
> Use Roboto font instead of open sans

- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferDbConnector.groovy
- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/viewmodel/OfferOverviewModel.groovy
The current offer retrieval is based on the project title only. 
This leads to numerous undesired side-effects. The retrieval is now
based on the offer id, which is supposed to be unique.
> Introduce proper offer retrieval

- qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/affiliation/create/CreateAffiliation.groovy
- qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/affiliation/create/CreateAffiliationOutput.groovy
- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/presenters/CreateAffiliationPresenter.groovy
**Purpose**
The method `successNotification` was missing in the interface but still used, this might cause problems at some point since the actual method implemented in the present was shown as unused although in use.
**Changes**
Add the method to the output interface of the create affiliation use case
> Add successNotification method to create affiliation 

- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/CreateAffiliationView.groovy
- qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/CreateCustomerView.groovy
- Change "department" to "address addition" to comply with labeling in other view
- Make description more informative
- Capitalize descriptions in "create customer" and "create affiliation" tabs
- Use editable dropdown for "create affiliation" organisation name to allow user to re-use existing names
> Fix #234 (naming of affiliation field)

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/products/ProductsDbConnector.groovy
- offer-manager-app/src/test/groovy/life/qbic/portal/qoffer2/products/ProductsDbConnectorSpec.groovy
- offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/OfferSpec.groovy
- offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/create/CreateOfferSpec.groovy
This fix is intended to adapt the q-offer-manager product to adapt to the inclusion of the productId in the individual products. 
See PR [here](https://github.com/qbicsoftware/data-model-lib/pull/146).
> Include productId in product accession in database connector and tests

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
Fixes #260 by setting the Locale.US of the offer date explicitly in the Offer PDF
> Specify Locale.US for offer-date in OfferPdf

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/persons/CustomerDbConnector.groovy
Fixes #332 
The affiliations of the new customer were wrongly added to the list of affiliations of the old customer and therefore duplicated in a later method.
> Remove duplicate affiliation creation

- offer-manager-domain/src/main/groovy/life/qbic/business/products/ProductDataSource.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/archive/ArchiveProduct.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/archive/ArchiveProductInput.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/archive/ArchiveProductOutput.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/copy/CopyProduct.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/copy/CopyProductInput.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/copy/CopyProductOutput.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/create/CreateProduct.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/create/CreateProductInput.groovy
- offer-manager-domain/src/main/groovy/life/qbic/business/products/create/CreateProductOutput.groovy
This PR adds the code structure for the interfaces of the service product maintenance interface
Adapted the folder structure of the domain of the project and defined the interface method of the use cases CreateProduct, CopyProduct and ArchiveProduct
> Add product maintenance interfaces

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
- offer-manager-app/src/main/resources/offer-template/offer.html
- offer-manager-app/src/main/resources/offer-template/stylesheet.css
This PR reintroduces the subtotal footers for each product group in the offer pdf outlining the overhead, total and net cost for each group with dummy data as was requested in #360.
> Introduce subtotal footers to product groups in Offer PDF 

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
This PR is intended as a temporary fix for the footer overflow problem by increasing the space allocated for the subtotal footers. (See #389)
Additionally it fixes a break occuring if not all productgroups are filled with products
> Fix Footer-Overflow and breaking in case of missing productgroups in Offer PDF 

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/update/UpdatePersonView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/update/UpdatePersonViewModel.groovy
Addresses #440 
This PR adds a button to add a new affiliation for a person when updating it. 
It also adjusts when an affiliation is valid by making the validity depending on the addressAdditionCombobox instead of the organisationComobox. This is required to allow to enable the add button correctly.
> Add 'add affiliation' button to update person

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/GridUtils.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/CustomerSelectionView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonViewModel.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/product/create/CreateProductView.groovy
1.0.0-alpha.6 (2021-04-13)
-----------------------------------
**Added**
* Filter message in grids is now dependent on column ID (<https://github.com/qbicsoftware/offer-manager-2-portlet/pull/457>)
* Add link to item table in offer pdf (<https://github.com/qbicsoftware/offer-manager-2-portlet/pull/469>)
**Fixed**
* Allow natural sorting of prices by their double value as opposed to their String representation (<https://github.com/qbicsoftware/offer-manager-2-portlet/pull/458>)
* Update position of country string in affiliation summary during customer creation (<https://github.com/qbicsoftware/offer-manager-2-portlet/pull/453>)
* Input fields of the CreateProductView are cleared after successful product creation(<https://github.com/qbicsoftware/offer-manager-2-portlet/pull/454>)
* Shows …
> Release 1.0.0-alpha.6

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
The sub-process responsible for rendering the PDF from the HTML template terminates after a given amount of time (10 seconds).
We use chromium as a renderer in a headless state. Since a failure of the rendering does not necessarily terminate the chromium process, the waitFor can, in certain cases, block the portlet indefinitely.
> Add timeout to rendering subprocess

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/GridUtils.groovy
This PR allows resetting the date picker by deleting the date content and obtaining the original list of all offers.
> Allow date picker reset

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonView.groovy
Fix for issue #492. A simple solution, to auto-select the first option in the address addition combobox after an organization has been chosen.
> Select first available address addition as default value

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
Addresses #562 by continuing the enumeration of the items in the offer pdf across all product groups
**To Test** 
Download an Offer PDF and check the enumeration of the individual items across the productgroups
> Continue item enumeration over all productgroups

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/OfferDbConnector.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/OfferOverview.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/OverviewService.groovy
This PR addresses #576 by introducing the name of the Project Manager associated with an offer as a filterable column to the `OfferOverview` View.
It also includes the necessary changes to the offer overview viewmodel, the database and the associated services. 
To allow for the inclusion of the Project Manager in the `OfferOverview` viewmodel, i had to deprecate the current `OfferOverview `constructors and introduce new constructor which include the name of the project manager as a string parameter. 
This is necessary since we currently employ 2 seperate constructors for creating an `OfferOverview`, which are distinct only be either needing a `ProjectIdentifier` or an empty string as a parameter.
Demo here: …
> Introduce filterable Project Manager column to OfferOverview 

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
- offer-manager-app/src/main/resources/offer-template/offer.html
Addresses #592 by introducing the overhead cost and ratio rows to the summary table on the first page in the offer pdf. 
The values of which are dynamically determined from the offer DTO. 
Example Screenshot:
> Include Overhead Ratio and Price in overview on first page

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/projects/ProjectDbConnector.groovy
- Removes connection object that was not closed and uses object of parent method
- Fixes #558
> Reuse connection from caller

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
- offer-manager-app/src/main/resources/offer-template/offer.html
- offer-manager-domain/src/main/groovy/life/qbic/business/offers/Offer.groovy
- offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/create/CreateOfferSpec.groovy
Addresses #575 by checking if the country of an affiliation associated with an Offer is set to "Germany" during offer Creation/Update. 
If that is not the case the taxation amount of the offer is set to 0.
This is also done in the Offer PDF printout and an additional statement indicating this change is added to the first page of the pdf. 
**Technical Details** 
The VAT Taxation rate is only applied if the `AffiliationCategory` of the Offer Affiliation is set to a enum value that differs from `INTERNAL` and the Affiliation `Country` property is set to "Germany". 
Also this PR doesn't change the values associated with offers already stored in the database. 
Currently the statement "Vat is non-applicable for offers outside of Germany" is …
> Taxes are also not applicable for customers from abroad

- CHANGELOG.rst
- offer-manager-app/src/main/resources/offer-template/offer.html
This PR moves the table header below the section/product category titles in the the Offer html template 
Note that this doesn't change anything in the dynamically created offer pdf.
> Move table header below category titles in productitem tables

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
- offer-manager-app/src/main/resources/offer-template/offer.html
- offer-manager-app/src/main/resources/offer-template/stylesheet.css
Addresses #613 by adapting the dynamically changed layout to the html template. 
1. Introduce acronyms for the individual productCategories.
2. Add the acronyms to the table title and the net price listing in the subtotal footer of each productCategory table.  
3. Removes the overhead and total cost in the subtotal footer of each productCategory table. 
4. Rewrite final total pricing footer to match html template. 
5. Adapt the spacing calculation for each page hosting a productCategory table to avoid overflow into the fixed page footer.
6. Introduce `ItemPrintOut.pageBreak` method which is used to dynamically set pagebreaks when a page has no spacing left. 
7. Introduce `ItemPrintout.createNewTable` method which is used to create the scaffolding to which new …
> Implement layout changes in offer PDF 

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/product/MaintainProductsView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/product/create/CreateProductView.groovy
fixes #640 
With this PR I placed the product panel into the views layout, to avoid the panel being part of the Create and CopyProductViews. 
Furthremore, I realised that the views are jumping if you switch between them and fixed it by using the right layout and setting margin to false
> Wrong product description display

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/update/UpdatePersonView.groovy
This PR closes #656 by disabling the "add affilation" button until a new affilation is selected. 
This also happens if customer was updated previously. 
**Miscellanous** 
Please note, that currently the update person button can only be clicked after a new organisation is selected, even if a new affilation was added to the customer. This is addressed in #655 
https://user-images.githubusercontent.com/29627977/121347170-29f8a280-c927-11eb-9c3d-ad74d327f11d.mov
> Disable add affilation button until a new affilation is selected

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferFileNameFormatter.groovy
Addresses #685 by replacing the PDF Prefix "Q" with the Offer Prefix "O" in the offer pdf file name. 
Additionally, it removes the "v" before the <offer_version> in the offer pdf filename.
> #685 Match Offer PDF filename to Offer ID Prefix 

- offer-manager-domain/src/main/groovy/life/qbic/business/offers/QuantityDiscount.groovy
Makes the discount calculation return a big decimal to decrease the likelihood of rounding numbers.
> Increase accuracy of quantity discount

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/offergeneration/QuotationDetails.groovy
This PR addresses the footer overflow introduced by the inclusion of discount productItems in the offer PDF. 
This PR adds approximations for for the space per page to host the individual table elements. 
Additionally it removes the redundant subtable generation for the individual productGroup tables. 
Lastly the necessary space is now calculated before the page break is introduced to avoid cutoffs after the table title or table header but before the first item of a productGroup. 
The values are now derived from manually measuring the space for each tableitem. However there is a slight variance since the linespace occupied by a linebreak in the productitem is bigger than the linebreak generated by the …
> Adapt Spacing Of generated productItems to avoid overflow into the footer

- CHANGELOG.rst
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy
Check before removing an extension whether the extension is there or not.
> FileDownloaders are not removed if they are not added first

- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectView.groovy
- offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectViewModel.groovy
Addresses a bug report from a user, that for
repeating project creation in the same space, the space name
was not saved from the previously generated project ID.
This commit will save the last space name used in the project
creation and re-use it, to increase effectivity during
recurring project creation within the same space.
> Re-use previously selected space in project creation
