qbicsoftware/offer-manager-2-portlet

CHANGELOG.rst
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/CustomerDbGateway.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/create/CreateCustomer.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/create/CreateCustomerInput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/create/CreateCustomerOutput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/update/UpdateCustomer.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/update/UpdateCustomerInput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/update/UpdateCustomerOutput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/OfferDbGateway.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/OfferExporter.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/create/CreateOffer.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/create/CreateOfferInput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/create/CreateOfferOutput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/search/SearchOffers.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/search/SearchOffersInput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/search/SearchOffersOutput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/update/UpdateOffer.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/update/UpdateOfferInput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/update/UpdateOfferOutput.groovy
qoffer-domain/src/test/groovy/life/qbic/portal/portlet/customers/create/CreateCustomerTest.groovy

~~Referenced issue is linked~~
~~If you've fixed a bug or added code that should be tested, add tests!~~
This commits creates empty classes and their structure.
Descriptions of the classes will follow in following commits

Add empty classes for qoffer-domain

---

qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/CustomerDbGateway.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/SearchCriteria.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/customers/CustomerDbConnector.groovy

Adds the interface methods defined in the architecture to the code

update methods of CustomerDbGatewy

---

pom.xml
qoffer-infrastructure/pom.xml

update the parent-POM to remove cyclic dependencies

update parent pom to 3.0.0

---

CHANGELOG.rst
pom.xml
qoffer-domain/pom.xml
qoffer-infrastructure/pom.xml

This PR should solve some dependency convergence issues for groovy libraries. Also, the data model lib version for the project has been pinned in the root pom, the modules only reference it. Like this, we can ensure that the data model version is same in the modules all the time.
Please state any technical details such as limitations, reasons for additional dependencies, benchmarks etc. here.
Add any other context or screenshots here.

Fix: converge dependencies

---

pom.xml
qoffer-infrastructure/pom.xml

Upgrade the parent POM to fix the java-connector security issue
Handle the versioning of the dependency in the parent POM

Upgrade parent POM to 3.1.0

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/DependencyManager.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/database/DatabaseSession.groovy

TK and I moved the Configuration Manager from the Database session class to the Dependency Manager to keep the dependency flow coherent

Move ConfigurationManager to DependencyManager

---

qoffer-domain/src/test/groovy/life/qbic/portal/portlet/customers/create/CreateCustomerSpec.groovy
qoffer-infrastructure/src/test/groovy/life/qbic/portal/qoffer2/database/DatabaseSessionSpec.groovy

This PR replaces the tests for the CreateCustomer use case

Implement working CreateCustomer tests

---

qoffer-domain/src/main/groovy/life/qbic/portal/portlet/customers/search/SearchCustomer.groovy

Adds the alternative path for use case SearchCustomer, when no customer entry with the given search criteria was found.

Implement customer not found aPath

---

qoffer-domain/src/main/groovy/life/qbic/portal/portlet/products/ListProducts.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/products/ListProductsDataSource.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/products/ListProductsInput.groovy
qoffer-domain/src/main/groovy/life/qbic/portal/portlet/products/ListProductsOutput.groovy

**Purpose**
Some classes accidentally were called package and not product as indicated with the dtoss
**Change**
Rename package classes to product

Name Package to Product

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/UpdateCustomerView.groovy

**Purpose of this PR**
This PR removes the UpdateCustomerView implementation since it's just a copy of an outdated alpha version of the CreateCustomerView implementation. Thanks @KochTobi for pointing it out here #67 
**Misc**
I'd argue that implementing the view from scratch makes more sense, since we didn't discuss the use case and it's implementation as of yet and a lot has changed since the first implementation of the createCustomerView

Remove outdated UpdateCustomerView implementation

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/CreateCustomerView.groovy

This PR provides a panel that shows detailed 
affiliation information, once a user has selected
an affiliation from the dropdown list.

Show affiliation details

---

qoffer-infrastructure/pom.xml

This PR adds the distribution management in order to deploy artifacts on our
Maven repository.
Other refactoring:
- Removed redundant maven clean up plugin

Provide artifact deployment on QBIC's Maven repo

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/customers/CustomerDbConnector.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/ButtonNavigationView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/CreateOfferView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/CustomerSelectionView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/OfferOverviewView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/ProjectInformationView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/ProjectManagerSelectionView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/SelectItemsView.groovy
qoffer-infrastructure/src/test/groovy/life/qbic/portal/qoffer2/database/CustomerDbConnectorSpec.groovy

**Purpose of change**
Add a navigation bar to indicate to the user the status of the current process
**Changes**
A ButtonNavigationView is generated included in the CreateOfferView
The bar is for now intentionally not clickable since it shall give the user an overview of the process, I am open to discuss if it is a requirement to make it clickable.

Add navigation bar

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/presenters/CreateAffiliationPresenter.groovy

It literally just sets the view to visible to ensure the view is visible

Remove Set Create affilation view to false in presenter

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/viewmodel/ViewModel.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/CreateCustomerView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/CreateOfferView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/PortletView.groovy

This PR displays an affiliation button, and enables the creation of a new affiliation during a new customer creation.
This PR also introduces a view history, to enable a simplified mechanism to go back to the last view.

Add create affiliation button

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/GridUtils.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/SearchCustomerView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/CustomerSelectionView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/ProjectManagerSelectionView.groovy

This PR adds filter to the customer selection and project manager selection list.
The static and generic method for adding filters has been extracted into an own class `GridUtils`, to reuse the code in different components of the app.

Add filters for grid columns

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferToPDFConverter.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/OfferOverviewView.groovy
qoffer-infrastructure/src/main/resources/offer-template/offer.html
qoffer-infrastructure/src/main/resources/offer-template/stylesheet.css

This PR updates the ids according to the html template and adds the missing dynamic features of an offer

Create html content dynamically

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/viewmodel/CreateOfferViewModel.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/CustomerSelectionView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/ProjectManagerSelectionView.groovy

Refresh data provider for grids upon list change

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferToPDFConverter.groovy

**Purpose**
The date was not properly formatted as desired.
**Changes**
The offer now indicates the date now in the form of DAY, d MONTH yyyy

make current date more concrete!

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/controllers/CreateOfferController.groovy

fixes #204 
The project title of an offer is now the project title and the description is the description

swap description and title

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferToPDFConverter.groovy

**Purpose of change**
#192 
**Changes**
Swap the variables so that the net displays the net value and the estimated total displays the estimated total.

swap prices

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferToPDFConverter.groovy
qoffer-infrastructure/src/main/resources/offer-template/offer.html
qoffer-infrastructure/src/main/resources/offer-template/stylesheet.css

This PR takes the offer product items and renders
them properly in the final PDF printout of the offer.

Render selected product items in PDF

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/offers/OfferToPDFConverter.groovy
qoffer-infrastructure/src/main/resources/offer-template/offer.html

**Purpose**
Fix #231 
**Changes**
Updated the variable name to be more specific and update the price value by choosing the correct value

Fix total cost net on offer PDF

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/OfferOverviewView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/SelectItemsView.groovy

This PR adds filters for the columns "Product Name" and "Product Description".

Provide filter for service products and selected items

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/OfferOverviewView.groovy

This PR removes already existing file download extensions on the offer download button.

Remove existing file download extensions

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/viewmodel/UpdateOfferViewModel.groovy

Clears the selected products before loading them.

Clear product item list on update offer

---

qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/OverviewView.groovy
qoffer-infrastructure/src/main/groovy/life/qbic/portal/qoffer2/web/views/create/offer/OfferOverviewView.groovy

Offer PDFs have the offer id as filename

Offer PDFs have the offer id as filename

---

CHANGELOG.rst
README.rst

**Purpose**
Update the documentation of the software to reflect the current status
fixes #122

Update software documentation

---

qoffer-domain/src/main/groovy/life/qbic/portal/portlet/offers/identifier/RandomPart.groovy

This PR implements the random id part and provides
a four letter random String of German alphabet letters.

Create four letter long random part

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/affiliation/create/CreateAffiliationView.groovy

Reintroduces changes from PR #280 that were lost in the great merging catastrophe of 2021.

reintroduce changes from Fix #234

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/AppView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/affiliation/create/CreateAffiliationView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/CreateOfferView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/CustomerSelectionView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/OfferOverviewView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/ProjectInformationView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/ProjectManagerSelectionView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/SelectItemsView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonView.groovy

**Purpose**
fix #235 
**Changes**
Adjust the margin of the respective layouts such as `OfferOverviewView` and others

Fix portlet content alignment

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/SelectItemsView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/products/ProductsDbConnector.groovy
offer-manager-app/src/test/groovy/life/qbic/portal/qoffer2/products/ProductsDbConnectorSpec.groovy

Description of changes
This PR includes the productId in the SelectItemsView as was requested in #275 and its implementation can be seen in the following screenshots:

Collect ProductId from DB and show it in SelectItemsView

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/affiliation/create/CreateAffiliationView.groovy

fix syntax error introduced by change from field to combobox

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/AppPresenter.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/persons/CustomerDbConnector.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/create/CreateCustomer.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/create/CreateCustomerDataSource.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/create/CreateCustomerInput.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/update/UpdateCustomer.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/update/UpdateCustomerDataSource.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/update/UpdateCustomerInput.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/update/UpdateCustomerOutput.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/customers/update/UpdateCustomerInputSpec.groovy

tests missing, just a draft for now

implement update customer use case(s)

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/SelectItemsView.groovy

Fixes #246 by removing the quantity field from the ProductItemsGrid in the SelectItemsView

Remove quantity field from SelectItemsView

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy

Provide requested file name format for offers

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferManagerApp.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/AppView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/StyledNotification.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/CreateOfferPresenter.groovy

I took the freedom to give the notification messages some refinement on Friday afternoon.
The goal was to make the notifications more present in the application and closable by indicating it via a `close` button.

Shape style notifications

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/person/create/CreatePersonViewModel.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/customers/affiliation/create/CreateAffiliation.groovy

Fix affiliation creation failure

---

CHANGELOG.rst
README.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferToPDFConverter.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/OfferOverviewView.groovy

Introduces support for configurable chromium executable

---

CHANGELOG.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/OfferOverviewView.groovy

Make the offer controls more intuitive

---

CHANGELOG.rst
offer-manager-app/src/main/resources/offer-template/offer.html

Update agreement text in offer pdf

---

AUTHORS.rst
CHANGELOG.rst
README.rst
offer-manager-app/pom.xml
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/DependencyManager.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/OfferManagerApp.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/AppView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/AppViewModel.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/security/Role.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/security/RoleService.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/security/liferay/LiferayRoleService.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/security/local/LocalAdminRoleService.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/security/local/LocalManagerRoleService.groovy
offer-manager-app/src/main/webapp/WEB-INF/liferay-display.xml
offer-manager-app/src/main/webapp/WEB-INF/portlet.xml
offer-manager-domain/pom.xml
pom.xml

This draft shows an example implementation that will provide role-based feature access to users of the offer manager application.

Provide user role example

---

offer-manager-domain/src/main/groovy/life/qbic/business/offers/create/CreateOfferInput.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/projects/create/CreateProjectInput.groovy

Exchanges the offer with the project application DTO in the input interface of the CreateProject use case.

exchange offer with project application

---

offer-manager-domain/src/main/groovy/life/qbic/business/projects/spaces/CreateProjectSpace.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/projects/CreateProjectSpaceSpec.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/projects/CreateProjectSpec.groovy

**Purpose**
Implements the CreateProjectSpace use case
**Changes**
Implements the use case domain of the CreateProjectSpace use case and adds tests

Implement create project space domain

---

offer-manager-domain/src/main/groovy/life/qbic/business/projects/create/CreateProject.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/projects/create/CreateProjectInput.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/projects/spaces/CreateProjectSpace.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/projects/CreateProjectSpaceSpec.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/projects/CreateProjectSpec.groovy

**Purpose**
Implement the domain logic of the CreateProject use case
**Changes**
Adds and implements the CreateProject use case and connecting it to the respective interfaces

Implement create project domain

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectController.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectPresenter.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectViewModel.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/projects/create/CreateProject.groovy

Adds the create project component.

Add component create project

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/DependencyManager.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/projectcreation/CreateProjectViewModel.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/OfferDbConnector.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/ProjectAssistant.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/projects/ProjectDbConnector.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/projects/ProjectMainConnector.groovy

This PR links a created project with an offer and lists an associated project in the offer overview.

Incorporate project link

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/CreateOfferViewModel.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/products/ProductsDbConnector.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/offers/Offer.groovy

This PR fixes three issues:
1. It addresses the missing productCategories "Proteomics" and "Metabolomics" in the ProductDBConnector while storing a product and retrieving a product
2. It updates the Overhead and No Overhead Lists and Calculation methods in the offer entity to account for Proteomic and Metabolomic Products
3. It includes the new ProductCategories to the CreateOffer Viewmodel to enable the correct startup of the ViewModel.

Introduce ProductCategories to ProductConnector and update Offer Pricing 

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/OverviewService.groovy
pom.xml

Please state what you've changed and how it might affect the user.
Please state any technical details such as limitations, reasons for additional dependencies, benchmarks etc. here.
Add any other context or screenshots here.

Fix overview renewal

---

CHANGELOG.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/product/MaintainProductsView.groovy

* Use a column renderer for total price formatting
* Fixes unexpected ordering of prices which was caused by ordering formatted Strings

Sort by price

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/GridUtils.groovy

Move the location of the null check and prevent errors to go unnoticed

Move null check and log error

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/OfferOverviewView.groovy

Offer overview organisation polishing

---

offer-manager-app/src/main/resources/offer-template/offer.html

update link test

---

CHANGELOG.rst
offer-manager-domain/src/main/groovy/life/qbic/business/products/create/CreateProduct.groovy

Fix wrong error message

---

CHANGELOG.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/GridUtils.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/overview/OfferOverviewView.groovy

This PR adds a column filter method that allows to filter for a custom BiPredicate<V,String> where the String is the user input and the V is the type of value contained in this column.

Add column filter method that accepts a custom predicate

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/GridUtils.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/project/ProjectIdContainsString.groovy

Adds a missing check to the productId filter

Pass all entries for empty user input

---

CHANGELOG.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/OfferOverviewView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/SelectItemsView.groovy

Limit rows when creating offer

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/offergeneration/QuotationDetails.groovy
offer-manager-app/src/main/resources/offer-template/offer.html

Fixes the overflow into the footer introduced by changing the div order in the html template 
This was supposed to be in the #683 PR but wasn't pushed correctly 🤦

Fix Footer spacing

---

CHANGELOG.rst
offer-manager-domain/src/main/groovy/life/qbic/business/offers/OfferItem.groovy
offer-manager-domain/src/test/groovy/life/qbic/business/offers/OfferItemSpec.groovy

This PR adds a new DTO to transfer the information required on an offer

Add offer item

---

offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/OfferSpec.groovy

Improves the tests for overhead calculation so that they can be changed more quickly and are more explicit in the log.

Improve tests for overhead calculation

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/offergeneration/QuotationDetails.groovy

I screwed up the branch, this should fix that

adapt to feedback and fix stuff

---

offer-manager-domain/src/main/groovy/life/qbic/business/offers/content/CreateOfferContent.groovy
offer-manager-domain/src/test/groovy/life/qbic/business/ProductFactory.groovy
offer-manager-domain/src/test/groovy/life/qbic/business/offers/CreateOfferContentSpec.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/OfferSpec.groovy

Substract discount from category sum

Add discounts in category net.

---

offer-manager-domain/src/main/groovy/life/qbic/business/offers/Offer.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/OfferSpec.groovy

Account for discounts before calculating overheads

Remove discount for overhead calculation

---

offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/offers/OfferDbConnector.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/offers/Converter.groovy

Stores the total discount in the db

Store total discount in database

---

offer-manager-domain/src/main/groovy/life/qbic/business/offers/identifier/OfferId.groovy

Correct offer id format

---

CHANGELOG.rst
offer-manager-domain/src/main/groovy/life/qbic/business/offers/Offer.groovy
offer-manager-domain/src/test/groovy/life/qbic/business/offers/OfferContentSpec.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/OfferSpec.groovy

Fixes #775
I rounded now the total discount, as you can see in the PR. Please speak up if you think that is the wrong place to do so.
Furthermore, I added a test reflecting the issue. It failed before I added the rounding, you can try it out locally if you want :)

Fix rounding issue

---

offer-manager-app/src/main/resources/offer-template/stylesheet.css

Increase spacing in cost summary

Increase spacing in cost summary

---

CHANGELOG.rst
offer-manager-app/src/main/resources/offer-template/offer.html

Update html template

---

CHANGELOG.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/CreateOfferViewModel.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/components/offer/create/SelectItemsView.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/dataresources/products/ProductsDbConnector.groovy
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/offergeneration/OfferTemplate.groovy
offer-manager-app/src/main/resources/offer-template/offer.html
offer-manager-app/src/main/resources/offer-template/selectors.txt
offer-manager-domain/src/main/groovy/life/qbic/business/offers/Offer.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/offers/OfferContent.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/offers/TaxOffice.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/offers/content/CreateOfferContent.groovy
offer-manager-domain/src/main/groovy/life/qbic/business/products/Converter.groovy
offer-manager-domain/src/test/groovy/life/qbic/business/ProductFactory.groovy
offer-manager-domain/src/test/groovy/life/qbic/business/offers/TaxOfficeSpec.groovy
offer-manager-domain/src/test/groovy/life/qbic/portal/portlet/offers/OfferSpec.groovy
pom.xml

This PR adds a complete user story, where a project manager wants to add external services to an offer.

User story: add external services to offer

---

CHANGELOG.rst
offer-manager-app/src/main/groovy/life/qbic/portal/offermanager/offergeneration/OfferTemplate.groovy
offer-manager-app/src/main/resources/offer-template/offer.html
offer-manager-domain/src/main/groovy/life/qbic/business/offers/OfferContent.groovy

This addresses [DM-34](https://qbicsoftware.atlassian.net/browse/DM-34)
The address addition (if any) is now shown in the offer PDFs for the selected customer.

DM-34 Provide customer's address addition on offer pdf

---

CHANGELOG.rst
offer-manager-app/pom.xml
offer-manager-app/src/main/resources/offer-template/offer.html
offer-manager-domain/pom.xml
pom.xml

1.2.7 (2022-01-24)
------------------
**Added**
* Update publication acknowledgement template text in offer template (#884)
**Fixed**
**Dependencies**
**Deprecated**

Hotfix 1.2.7
